FROM rust:1.56.0-alpine AS noria-server

RUN apk add --no-cache \
        alpine-sdk \
        openssl-dev \
        libc-dev \
        pkgconf \
        llvm \
        clang \
        mysql-client

WORKDIR /tmp/noria

COPY . ./

RUN cargo build --release --workspace